apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-flask-test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml 
    path: helm_files 
    repoURL: https://github.com/raita0100/CI_automation_test 
    targetRevision: HEAD
