apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: cicdtest
    name: cicdtest
    namespace: test
  spec:
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: cicdtest
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
